.TH Flopenr_32 7 "October 2020" Linux "FIUCIS-CDA Hardware Manual"
.SH MODULE NAME
Flopenr_32
.SH DEPENDENCIES
.I
Flopenr,
DESwitch,
DSwitch
.
.SH INPUTS
.TS
tab(;) allbox;
c;c.
Name;Size(Bits)
clk;1
reset;1
E;1
D;32
.TE
.SH OUTPUTS
.TS
tab(;) allbox;
c;c.
Name;Size(Bits)
Q;32
.TE
.SH DESCRIPTION
A 32-bit enabled register.
.
.SH BUGS
Working on recursive dependency download for hardware.
.SH AUTHOR
Alexander T Pastoriza
.SH "SEE ALSO"
.BR qms (1),
.BR modclone (1)
